[workspace]
authors = ["Hans Fangohr <fangohr@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "music-pedalboard-spectrum-analysis"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"
numpy = ">=2.3.3,<3"
jupyter = ">=1.1.1,<2"

[pypi-dependencies]
sounddevice = ">=0.5.2, <0.6"
